### ISSUE TITLE
Fails to install on Linux/Windows brackets 1.2

### ISSUE THREAD

**Issue by Dorza** [jasonsanjose/brackets-sass#109]
Tried many times on my home machine (Linux Mint 17) to install this plugin via URL, manually and via ZIP and it fails each time. Then thought it's something quirky with nix so tried on my work machine (Win 8 with ruby installed (I use notepad++ for sass work usually) and same thing happens..."Installation Failed, the extension encountered an error while starting up". 

In the console I get the following "

GET file:///home/my_machine/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/thirdparty/source-map/lib/source-map/source-map-consumer.js
in file  require.js:1903

[Extension] failed to load /home/my_machine/.config/Brackets/extensions/user/jasonsanjose.brackets-sass - Module does not exist: file:///home/my_machine/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/thirdparty/source-map/lib/source-map/source-map-consumer.js  

in file/utils/ExtensionLoader.js:220

**Comment by jasonsanjose** [comment]
Have you tried installing via extension manager instead of by URL?

**Comment by Dorza** [comment]
Hi thanks for the speedy reply. Previously I couldn't find brackets-sass within the extention manager. Its there now and got it installed, fantastic :). Thanks
