### ISSUE TITLE
Live Preview in partials requires saving

### ISSUE THREAD

**Issue by MattDiMu** [jasonsanjose/brackets-sass#113]
This bug actually happens quite a lot to me. In imported files, the Live Preview only updates Chrome after saving the file. In the "main.scss"-file (which imports the partials), the live-preview works without saving the file.

I know, this description probably doesn't help you much, but how could i assist you reproducing it?

Btw, I'm using Win7 and the latest brackets (1.3) & brackets-sass version.

edit: tested it on OS X (v 10.9.5) and here it happens as well.

edit2: I've found 2 cases in which the Live Preview NEVER works:
1. If a new partial is added and imported. Restarting Live Preview is required for live Preview to work.
2. If a partial is imported in another partial (nested imports). e.g. main.scss imports "partial/_first.scss", which imports "_second.scss". If the import happens directly in the main.scss file, it works (after a Live Preview restart).

It seems to me like
- imports are not watched recursively (only the ones imported directly in the main file)
- Live Preview struggles when new files are added and imported (restart solves  this issue)

**Comment by Turqueso** [comment]
@MattDiMu did you try adding the path of your folder for partials on the ```.brackets.json```?
```"includePaths": [  
 "partials/"  
],```
