### ISSUE TITLE
[Q] Someone can help me ?

### ISSUE THREAD

**Issue by Amstramgram** [jasonsanjose/brackets-sass#117]
Hi, 
my problem it's: i don't know how config .brackets.json with my project. Someone can help me?
 
.brackets.json
index.html
- assets
- - stylesheets
- - - css
- - - - main.css // output
- - - sass 
- - - - main.sass // with import
- - - - modules.sass
- - - - reset.sass
- - - - other.sass

thank you.

**Comment by nicolo-ribaudo** [comment]
This should be enough:
```json
{
  "path": {
    "assets/stylesheets/sass/*.sass": {
      "sass.options": {
        "optputDir": "../css/"
      }
    }
  }
}
```

If `modules.sass`, `reset.sass`, and `other.sass` are partials (i.e. files imported only from other `.sass` files), they should be named with a `_` at the beginning (`_modules.sass`, `_reset.sass`, and `_other.sass`) and imported as this:
```css
@import "modules";
@import "reset";
@import "other";
```

**Comment by anejskubic** [comment]
@nicolo-ribaudo can you help me with my customization, because I can't figure it out which folder sass is watching for changes? So when I'm changing partials in import, my home.scss & products.scss is not compiling automatic.

I have folders like this:
```javascript
+ assets/css
| --- + scss
       | --- + compiled /* folder in which is *.css.map */
       | --- + import
              | --- defaults.scss
              | --- variables.scss
              | --- footer.scss
              | --- header.scss
              | --- ...
       | --- home.scss
       | --- products.scss
| --- home.css
| --- products.css
```

my **.bracket.json**:
```javascript
{
    "path": {
        "assets/css/scss/*.scss": {
            "sass.options": {
                "outputDir": "../",
                "sourceComments": false,
                "sourceMap": "scss/compiled/",
                "outputStyle": "compressed",
                "includePaths": [
                    "import/",
                    "compiled/",
                    "icons/"
                ]
            }
        },
		"assets/css/scss/import/*.scss": {
            "sass.options": {
                "outputDir": "../compiled",
                "sourceComments": false,
                "outputStyle": "compressed"
            }
        }
    }
}
```
**thanks in advance!**

**Comment by Turqueso** [comment]
What you say and your folders Confuse (Wich are partial? yout need `_`as prefix). But let me see if i goit it right.
home.scss and products.scss are your main file, those have the imports. The rest are partials.
```
{
    "path": {
        "assets/css/scss/home.scss": { /* path of the file containing the @import of partials */
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../", /* output dir is assets/css/ */
                "includePaths": [
                    "import/", /*folder with the partials */
                    "icons/" /* Does this contain partials? */
                ],
                "sourceComments": false,
                "outputStyle": "compressed"
            }
        },
      "assets/css/scss/products.scss": { /* same but with the other main file */
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../", /* output dir is assets/css/ */
                "includePaths": [
                    "import/", /* is it using partials on same folder? */
                    "icons/" /* Does this contain partials? */
                ],
                "sourceComments": false,
                "outputStyle": "compressed"
            }
        }
    }
}
```

if `compiled`only contains the map and no partials you don't need to import it. I've not tested it but it should be something like that. Don't fonget to erase comments.

**Comment by anejskubic** [comment]
@Turqueso, yes **home & products** are main files and have partials in folders **import & icons**. And I know for _ sign for partials, but it doesn't auto compile home.scss & products.scss on change of any partial file.
I have changed all partials to ```_*.scss``` and rewrite *.brackets.json* but no luck.
@jasonsanjose do you have any idea what to do here?
