### ISSUE TITLE
warning when import "susy"

### ISSUE THREAD

**Issue by mukiwu** [jasonsanjose/brackets-sass#120]
I use brackets sass, but when I compile, it has wrong msg:

```
'Error: File to import not found or unreadable: susy.
...
```

so, does brackets sass not support susy?
thanks !

**Comment by nicolo-ribaudo** [comment]
Do you have Susy's files in your project?

In order to write
```css
@import "susy";
```



You should have a file named `_susy.scss` (or `.sass`)

**Comment by mukiwu** [comment]
@nicolo-ribaudo susy is a framwork based on compass, so it doesn't have any file in my project :(
here is documation: http://susydocs.oddbird.net/en/latest/install/#quick-start

**Comment by nicolo-ribaudo** [comment]
@mukiwu The problem is that brackets-sass runs `sass --compass` instead of `compass`. A workaround can be adding a `config.rb` file at the root of your project:
```ruby
require "susy";
```

**Comment by mukiwu** [comment]
@nicolo-ribaudo  yes, I already have it in my config.rb
![2015-05-19 2 16 18](https://cloud.githubusercontent.com/assets/3794103/7696626/89a480ae-fe31-11e4-9f4c-8d28ee3c9be4.png)
