### ISSUE TITLE
how to setting the path 

### ISSUE THREAD

**Issue by mukiwu** [jasonsanjose/brackets-sass#121]
here is my folder structure:

```
+ css/
|--- style.css
+ sass/
|--- _basic.scss
|--- _girds.scss
|--- _style.scss
|--- + component/
|------- _banner.scss
|------- _tab.scss
|--- + layout/
|------- _index.scss
|------- _sidebar.scss
```

so I have many particals , this is my json setting:

```
{
    "sass.enabled": false,
    "sass.compiler": "ruby",
    "sass.compass": true,
    "path": {
        "sass/*.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "output": "style.css",
                "includePaths": [],
                "sourceComments": true,
                "outputStyle": "nested",
                "sourceMap": false
            }
        }
    }
}
```

via the setting, it compile only when I edit style.scss, if I edit any partical files, it doesn't work.
does anyone know how to setting the path ? thanks

**Comment by nicolo-ribaudo** [comment]
brackets-sass uses source maps to know which files compile when a partial change, so you should enable them.

**Comment by flaviusemil** [comment]
I think that your problem is with this line of code `"output": "style.css",` try deleting it and see if it works.
You enabled sass for every ***sass*** file in **sass folder** but your output is always the same. Even if you modify another file it will only override ***style.css***.
