### ISSUE TITLE
Update LibSass to 3.2 / node-sass 3

### ISSUE THREAD

**Issue by Madebym** [jasonsanjose/brackets-sass#123]
Can we update manually somehow, or is it maybe slated for next version of the extension?

**Comment by nicolo-ribaudo** [comment]
> Can we update manually somehow

Unfortunately no, because of some API changes.

Upgrading to node-sass 3.0.0 (libsass 3.2.2) will also fix #92

**Comment by Madebym** [comment]
@nicolo-ribaudo Thanks for the insight. So, basically I just need to wait till upgrade to node-sass 3.0.0. happens?

**Comment by jasonsanjose** [comment]
I've updated the docs https://github.com/jasonsanjose/brackets-sass/blob/master/node/2.0.1/README.md to explain how node-sass upgrades should be handled.

**Comment by nicolo-ribaudo** [comment]
@jasonsanjose Are you working on this?

**Comment by jasonsanjose** [comment]
Not yet.

**Comment by nicolo-ribaudo** [comment]
I can work on this tomorrow

**Comment by nicolo-ribaudo** [comment]
PR #126

**Comment by Madebym** [comment]
@nicolo-ribaudo  Has your pull request been merged? How does these things work? 

Sorry, but I am total noob for these kind of stuff, need to brush up on front-end stuff, being primarily a designer.

**Comment by derwaldgeist** [comment]
The bootstrap-sass-official package is using the @at-root directive, which is only available in libsass-3.2:
https://github.com/sass/libsass/issues/353

This causes Brackets Sass to render invalid CSS. You won't notice it until you experience the following side-effects:
1. The glyphicon font included in bootstrap won't work
2. Meteor.js validation fails, which causes a Meteor application to break

So I would appreciate if libsass for Brackets could be updated to 3.2 as soon as possible.

Thanks and keep up the good work!

**Comment by jasonsanjose** [comment]
Fixed in #136
