### ISSUE TITLE
Qustion about the ..brackets.json

### ISSUE THREAD

**Issue by suhide** [jasonsanjose/brackets-sass#129]
My files tree is like this 
--index.htm
--scss
-------style.scss
--css
--.brackets.json

my.brackets.json is 
{
"themes.theme": "dark-theme",
"path": {
"scss/style.scss": {
"sass.enabled": true,
"sass.options": {
"outputDir": "../css/",
"imagePath": null,
"sourceComments": false,
"outputStyle": "compressed"
},
"linting.collapsed": false
}
},
"linting.collapsed": false,
"fonts.fontSize": "13px"
}
The .brackets.json seems didn't work..the CSS file stil contain the comments and compile in the same fold,not in the CSS fold.

Did I put the JSON file in the wrong place?

**Comment by MarcoWilli** [comment]
No, the .bracket.json is in the right directory. It needs to be in root. Try switching projects, Brackets will show you an error if your json file isn´t ok.

**Comment by jasonsanjose** [comment]
Thanks @MarcoWilli. That's correct. Closing.
