### ISSUE TITLE
SASS error: cleanup

### ISSUE THREAD

**Issue by bsebastian86** [jasonsanjose/brackets-sass#138]
The latest update creates an error with the exclamation (!) at the bottom saying, "cleanup". Does not compile anymore. Had to revert to previous version.

**Comment by pigmeu** [comment]
Same thing is happening to me, to every file i open! How can I revert?

**Comment by junias91** [comment]
I have the same problem :-(

**Comment by bhouszka** [comment]
Same issue here :(

**Comment by jasonsanjose** [comment]
Thanks for the reports. Working on it now.

**Comment by jasonsanjose** [comment]
Fixed in #141. Please try installing 2.0.3 and report back here. Thanks!

**Comment by bhouszka** [comment]
Works great now! thanks!

**Comment by SPAHI4** [comment]
still have this error on 2.0.3

**Comment by JTBringe** [comment]
This error started appearing as of today when I updated to release 1.8 build 1.8.0-17108 of Brackets (released Nov. 2 2016).

**Comment by kimanhle90** [comment]
I have this problem too.

**Comment by GrantColloty** [comment]
I too am having this issue after updating Brackets to 1.8.

**Comment by nanu-miguel** [comment]
I ma having the same issue after updating to Brackets 1.8 - Any fixes for this??

**Comment by JTBringe** [comment]
Several of the extensions I rely on stopped working after updating (such as eqFTP).
I ended up having to roll back to the previous version of Brackets (1.7) to get them working again.

**Comment by nanu-miguel** [comment]
That's not great @JTBringe - I also rely on a few extensions including GIT and Sass which don't work with version 1.8 - Oversight on behalf of the Brackets team?

Did you roll back or do a clean install?  Seems to be a clean install is the only option.

**Comment by jhechtf** [comment]
I too am still having this issue after updating brackets sass to 2.0.3

**Comment by K20** [comment]
Same here, with Brackets  1.8.0-17108 on windows.

**Comment by Humphreto** [comment]
Am having the very same problem of sass cleanup. what should i do

**Comment by donames** [comment]
I see no fix so far?  I guess I can ignore it.

**Comment by syahmi518** [comment]
got same issues .. Cleanup Error

**Comment by Rafiozoo** [comment]
https://github.com/jasonsanjose/brackets-sass/issues/190#issuecomment-319950279 this helped to me
