### ISSUE TITLE
Doesn't work since last update or before last update...

### ISSUE THREAD

**Issue by Jordane-L** [jasonsanjose/brackets-sass#143]
All is in the title...

It worked perfectly for several days and that no longer compiles

I don't know if this error correspond to that:

Document ref count has fallen below zero!ErrorNotification.js:125 window.console.error/document/Document.js:180 Document.releaseRef/editor/Editor.js:401 Editor.destroy/view/Pane.js:1093 Pane.destroyViewIfNotNeeded/view/Pane.js:1014 Pane.showView/editor/EditorManager.js:557 _showEditor/editor/EditorManager.js:627 openDocument/view/MainViewManager.js:1182 _edit/view/MainViewManager.js:1272 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.add/view/MainViewManager.js:1271 _open/document/DocumentCommandHandlers.js:323 _doOpen/document/DocumentCommandHandlers.js:393 _doOpenWithOptionalPath/document/DocumentCommandHandlers.js:450 handleFileOpen/document/DocumentCommandHandlers.js:498 handleDocumentOpen/command/CommandManager.js:97 Command.execute/command/CommandManager.js:291 execute/project/WorkingSetView.js:776 drop/project/WorkingSetView.js:815 (anonymous function)thirdparty.min.js:560 n.event.dispatchthirdparty.min.js:560 r.handle

My .jason file is always the same:

{
    "path": {
        "stylesheets/style.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "style.css",
                "outputStyle": "compressed",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": "map",
                "sourceMap": "style.css.map"
            }
        },
        "scss/import/*.scss": {
            "sass.enabled": false
        }
    }
}

Resulting file tree will appear as follows:

* + stylesheet
* |--- style.scss
* |--- style.css
* |------ + import
* |--------- colors.scss
* |--------- typography.scss
* |--------- reset.scss
* |--------- form.scss
* |--------- layout.scss

An idea ?

**Comment by Jordane-L** [comment]
edit: I tested with version 2.0.1, it works and I re tested 2.0.2 and 2.0.3 and this doesn't work

**Comment by anejskubic** [comment]
I think its problem on line: "sourceComments": "map", because "map" it's not supported any more, only true/false now .
Correct me if i'm wrong.

**Comment by Jordane-L** [comment]
thx for your comment but I tried your proposition and doesn't work so :'( 
![capture d ecran 2015-07-14 a 18 42 07](https://cloud.githubusercontent.com/assets/7188658/8676199/0e16d37a-2a59-11e5-9b54-02a183e59c59.png)

I stay for the moment with version 2.0.1

**Comment by anejskubic** [comment]
whit out " ! try: "sourceComments": true,
this should work :)

**Comment by Jordane-L** [comment]
@anejskubic What idiot I am ! Without "" it works :). Thanks you very much. :+1:
