### ISSUE TITLE
Checking for errors

### ISSUE THREAD

**Issue by weolo** [jasonsanjose/brackets-sass#147]
Loving your addon but I am having trouble getting it working while at work.
Whenever I view a sass file I see "Checking for errors" in the bottom right corner and the css never compiles.

There is also a yellow triangle which shows this:
1 SCSS Problem
SCSS has timed out after waiting for 10000 ms

Any help appreciated.

**Comment by EmixMaxime** [comment]
Hello, i also have this problem..

**Comment by weolo** [comment]
I had already added the "proxy" setting to brackets.json settings file so it was not that.
I figure out what it was for me in the end, I was using Windows XP at work and that does not work with Brackets SASS
