### ISSUE TITLE
Compile won't work for me

### ISSUE THREAD

**Issue by Amstramgram** [jasonsanjose/brackets-sass#148]
Hi, i have little problem for compile my file. I don't know if my .brackets.json is correctly write with my file tree.

**file tree**
```
.brackets.json
- assets
 - stylesheets
  - folder
   - _a.scss
  - folder
   - _b.scss
  - main.scss
```
*and in my main.scss, i have some import (a and b file)*

**.brackets.json**
```
{
    "sass.enabled": false,
    "path": {
        "assets/stylesheets/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "main.css",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": false,
                "outputStyle": "nested"
            }
        }
    }
}
```

thank you for your time and your help maybe.

**Comment by Turqueso** [comment]
@Amstramgram `output`is the path, not the final name for the file. It should be something like `"outputDir": "../stylesheets/",`

**Comment by Amstramgram** [comment]
In the doc, i read that

```
output
Type: String Default: <input sass file name>.css
File name to use for the output CSS file.
```
but it's ok for me i try tomorrow .

**Comment by Turqueso** [comment]
@Amstramgram my bad, i confused `output`with `outputDir`. Your `output`is fine but you are missing `outputDir`

**Comment by Amstramgram** [comment]
@Turqueso no problem. It's works now i compile my file main.css but only from main.scss not form partial file, i don't know why, so strange.

**Comment by Turqueso** [comment]
@Amstramgram I'm having issue with partials lately too, did you include the path on ` "includePaths": [],`?

**Comment by Amstramgram** [comment]
Yes, i include all file whit partial file
