### ISSUE TITLE
I don't know how to use it.

### ISSUE THREAD

**Issue by bigflipo** [jasonsanjose/brackets-sass#157]
Hello, I'm new here. I'm using Ubuntu Linux and I downloaded:
libsass-master and ran the make command. (I guess that's how you install it)
then I downloaded
jasonsanjose.brackets-sass.2.0.3-132
and dragged it into the brackets extension manager.
It installed correctly.
Then I made a scss file and an html file, and on the html I called a css file with the same name as the scss one, and saved and previewed, and nothing happened. I checked the folder and there is no css file there. What am I doing wrong?
I'm using 
Brackets Release 1.4 experimental build 1.4.0-16380 (release 273804eb3) 
build timestamp: Mon Jul 27 2015 06:50:54 GMT+0000

Thank you for your time and effort making great software for all the world

**Comment by JohJakob** [comment]
I used Brackets SASS for a while on OS X but now it doesn't output the CSS and CSS.MAP files anymore. I installed it via the extension manager and tried to remove and reinstall it but that doesn't work. I'm using the same Brackets version as @bigflipo.

**Comment by Turqueso** [comment]
@bigflipo did you created the [.brackets.json file?](https://github.com/jasonsanjose/brackets-sass#sample-bracketsjson-file)

**Comment by Insanityandme** [comment]
same issue as @JohJakob , have created a .brackets.json file

**Comment by NetOperatorWibby** [comment]
@bigflipo @Insanityandme Check out my blog post and see if it doesn't help! https://dsgn.io/thoughts/post/how-to-use-brackets-sass

**Comment by bigflipo** [comment]
@Turqueso sorry for the long delay, I wasn't able to answer. I didn't create the json file. So that must be it, I'm going to study how, thanks.

**Comment by Insanityandme** [comment]
Got it working!

**Comment by bigflipo** [comment]
Thanks all for your help, I will dig deeper for an answer before asking anything, from now on. sorry for wasting your time. thanks.
