### ISSUE TITLE
doesn't load changed settings

### ISSUE THREAD

**Issue by RiesenGurke123** [jasonsanjose/brackets-sass#172]
Hey your sass addon is realy nice,
but I am not able to configure it like I want it to be.
I have this in my .brackets.json:

````JSON
{
    "sass.enabled": false,
    "path": {
        "sass/*.sass": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css",
                "includePaths": [],
                "sourceComments": false,
                "outputStyle": "compressed",
                "sourceMap": false
            }
        }
    }
}
````

my project:

+ sass/
   + main.sass
+ css/                   <-- **here should the compiled files go in**
+ .brackets.json
+ some html files

ignoring the setting, the sass files are compiled like this:

+ sass/
   + main.css
   + main.css.map
   + main.sass
+ css/
   + *nothing*

**Comment by Rafiozoo** [comment]
Hi! Very like a last slash is needed to properly point a directory.
`"outputDir": "../css/"`

**Comment by RiesenGurke123** [comment]
It works neither with nor without the slash. Not Only the path is different from the expected, but the hole setting also.
I have `"sourceMap":false`, but the main.css.map is generated. And the output style isn't compressed.

**Comment by Rafiozoo** [comment]
So your settings are not included and Brackets SASS works on defaults.
Are you sure your **.bracket.json** is located in your root directory, and you have opened this project via Brackets menu: File → Open Folder... [Ctrl+Alt+O]
or file explorer context menu: _Open as Brackets project_ ?

**Comment by RiesenGurke123** [comment]
ahh now it works. Folder structure in brackets was /projects/projectXYZ/sass/...
moved .brackets.json one up in the hierarchy. 
Thank you verry much
