### ISSUE TITLE
"cleanup" error appears after having updated Brackets

### ISSUE THREAD

**Issue by JTBringe** [jasonsanjose/brackets-sass#180]
This error started appearing as of today (Nov. 10) when I updated to release 1.8 build 1.8.0-17108 of Brackets (released Nov. 2 2016).

**Comment by jessefisher** [comment]
I'm seeing this too and while I can save the Sass it doesn't update the CSS file and then I eventually get this error.

`SCSS has timed out after waiting for 10000 ms`

Same release of Brackets on Windows 10 Pro.

**Comment by bobbybol** [comment]
Having the exact same issue - updated - cleanup error - SCSS timeout after 10000 ms

**Comment by Hitunen** [comment]
Ditto. 1.8.0-17108 on Windows 7 with
"name": "jasonsanjose.brackets-sass",
"version": "2.0.3-132"

**Comment by ttomato1** [comment]
Same problem on a Windows 10 install.  Looks like the extension isn't compatible with the latest Brackets.  

I'm also getting a 
	Error: `libsass` bindings not found in C:\Users\<user>\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-x64-48\binding.node. 

I don't have that directory in my extensions directory-  closest is win32-ia32-11

**Comment by chachah** [comment]
Exactly same troubles for a week. 
Sorry. I couldn't wait for a patch. So I opted for the combination of NotePad++ and Scout App.

**Comment by jedeveraa** [comment]
best solution? just downgrade the brackets app to 1.7 uninstall the new brackets and reinstall 1.7.

**Comment by chachah** [comment]
Hi jedeveraa. I'm not sure that reverting to a previous version because the updates aren't failsafe was ever the really best solution for the reputation of any app. The developers' reactivity is. But after nearly a week I don't see any response here.

**Comment by jedeveraa** [comment]
hi chachah. yea, for the sake of getting back to work. its my best solution for now. i hope the owner of this plugin will update the version as soon as possible. :(

**Comment by AgamlaRage** [comment]
I posted the issue to Brakets repository.
Maybe someone can maintain this extension instead.

[https://github.com/adobe/brackets/issues/12914](https://github.com/adobe/brackets/issues/12914)

**Comment by sanpan93** [comment]
Same trouble with latest bracket version on Win10 pro. 
Doesn't work on all my projects using this extension for sass compilation.
I think i will pass on Atom + sass autocompile or with Grunt process - so frustrating

**Comment by OhligerJ** [comment]
Can confirm jedeveraa's solution. On my Windows 7 machine, using Brackets 1.7 with this plugin works, but I get the cleanup error using Brackets 1.8

**Comment by jedeveraa** [comment]
Hi sanpan93, i think is the best solution for now just to work with this plugin is to downgrade your version into 1.7. hope someone will update this plugin. :(

**Comment by AgamlaRage** [comment]
In Brackets 1.7 there are some important things that not working, like Eslint....
And file loading are really really slow compare to others text-editor, in 1.8 it's a bit better.
I can't downgrade my Brackets juste for compile my Sass file....

**Comment by jedeveraa** [comment]
hi @AgamlaRage, yeah it depends on our needs. so far all of my extensions are working on 1.7.

**Comment by AgamlaRage** [comment]
I'm not blaming you !!! :)
I just really want Brackets to have all I need to code !

**Comment by sanpan93** [comment]
I confirm it works with bracket 1.7 but as AgamlaRage said, some other extensions are in trouble in v1.7.
Best solution for me : stay with bracket 1.8 (or Atom) and use task manager (grunp or gulp) to compile, minify, autocomplete etc ...=> build and use a solid workflow not depending of an extension.
It's strange that there is only one sass compiler in Bracket, no ? Even the new version of Dreamweaver (!!) has integrate one !

**Comment by chachah** [comment]
Hi everyone, did you know "Scout App"? It's a standalone app which compiles sass/scss files in the background every time sass or scss files change, just like brackets-sass does. It does the job no matter which editor you use. That is to say you can go on using Brackets. It's a child's play.
https://github.com/scout-app/scout-app

**Comment by sanpan93** [comment]
Yes. A good solution for little projects
Prepros is doing sensibly the same thing too : https://prepros.io/

**Comment by UltraChilly** [comment]
I have absolutely no clue if this will work for everyone but here's a quick fix that did the trick for me : 
- reload brackets without extensions
- reload brackets with extensions, that resets the warning which now shows the name and location of the missing file. If you're like me you're missing binding.node inside the darwin-x64-48 folder (which doesn't exist) in the extensions folder.
- navigate to your extensions folder (on mac it's under users>yourName>library (hidden by default)>application support>brackets>extensions>user>jasonsanjose.brackets-sass)
- from there go to node>2.0.3>node_modules>node-sass>vendor>... and there you don't have a darwin-x64-48 folder, create it
- inside that new folder, download and paste the relevant binding.node file from https://github.com/sass/node-sass/releases
- rename the file binding.node
- reload brackets without extensions
- reload brackets with extensions
- voilà!

This is pretty dirty but it seems to do the job, no bugs so far. Still hoping for an update soon, though. Hope it helps.

**Comment by Humphreto** [comment]
@UltraChilly that is very confusing to me

**Comment by Humphreto** [comment]
@AgamlaRage i think Am going to shift to Atom editor completely

**Comment by ttomato1** [comment]
I've changed over to NetBeans.  Can't use a dev environment that won't compile Sass and as much as I like Brackets, I've given up waiting.

**Comment by UltraChilly** [comment]
@Humphreto Don't worry, it's a terrible solution anyway :p and Atom is definitely worth trying

**Comment by AgamlaRage** [comment]
I'm using [Koala](http://koala-app.com/) to autocompile my sass file for now, waiting for an update. (on Windows 10).
Koala is one of the recommended application to do that. See [http://sass-lang.com/install](http://sass-lang.com/install).
It's doing well the job, it's easy to setup.

Koala listen the files you want, and compile it when a change occured.
You can customize the output file name, and there is also some minification options.

I'm a huge fan of Brackets, and code-mirror synthaxing, I'm not moving from Brackets for this !

**Comment by miguelventura** [comment]
@UltraChilly, your solution works for me! Thank you :)

**Comment by AgamlaRage** [comment]
@UltraChilly , works for me too, on Windows 10.

On Windows, I needed the **win32-x64-48** node sass release.

**Comment by Humphreto** [comment]
@UltraChilly Before using Bracket editor i was a big fan of atom. Now am extremely addicted to bracket i found atom extremely hard to use -- I simply cant use anything else rather than bracket..

So i decided to downgrade my editor to the previous version that works fine with sass..... 👎 [https://github.com/adobe/brackets/releases/tag/release-1.7](url)

**Comment by brehouse** [comment]
@UltraChilly  worked for me, thanks!

@AgamlaRage Windows solution worked

**Comment by UltraChilly** [comment]
@Humphreto, @miguelventura, @AgamlaRage, @brehouse, and everyone else who tried my fix, It's probably best you remove the folder we added and update the plugin properly now it's fixed (so we don't break anything) ;)

**Comment by brehouse** [comment]
Hey - looks like the latest update doesn't account for windows

**Comment by UltraChilly** [comment]
@brehouse oh, my bad :'(

**Comment by AgamlaRage** [comment]
I didn't see any update too. Windows 10

**Comment by bobbybol** [comment]
For windows, you _could_ just update node-sass yourself. At least that's what I did right after I saw what was wrong, and it works fine. Assuming you have node installed, go to <you_user>\Appdata\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3 and put your cursor in the address bar, type `cmd` to open console, and type `npm install node-sass`. Now the extension is using latest version and correct binding.. Basically what @UltraChilly was doing before but a little more rigorous ;)

**Comment by Brainzyy** [comment]
@brehouse @jasonsanjose @AgamlaRage I only sent in a fix for macOS, I will send in more fixes shortly, when I have time.

**Comment by Humphrzy** [comment]
@AgamlaRage how did you get it done on win 10. please i need yelp.....please
Am dying without it... i have absolute no idea what nodes are

A  screen recording would real help

**Comment by gverm** [comment]
@jasonsanjose can you make a beta release so people can test my changes?

**Comment by AgamlaRage** [comment]
@Humphreto  to fix this on **Windows 10** I applied the @UltraChilly solution.
You need to follow the steps that he described.
But in windows you need to download the **win32-x64-48 node sass release** to make it work.
[https://github.com/sass/node-sass/releases](url)

**Comment by gverm** [comment]
@AgamlaRage This has been done in latest git as well, but the release has to be done first.

**Comment by gverm** [comment]
@Humphreto @brehouse I created a new release that fixes your issues here: https://github.com/Brainzyy/brackets-sass/releases/tag/2.0.4

**Comment by jasonsanjose** [comment]
@Brainzyy I unfortunately (and quite obviously 😞 ) haven't had the time to keep this extension updated. I can transfer the ownership of the extension on the Brackets registry to you if that works. Just let me know.

**Comment by gverm** [comment]
@jasonsanjose I can try and keep this updated, I have limited programming knowledge, but I can make sure node-sass is updated and that problems are dealt with. I would like to make a new release, so that people can update through Brackets.

**Comment by jasonsanjose** [comment]
@Brainzyy done.

**Comment by gverm** [comment]
@jasonsanjose EDIT: updated

**Comment by Humphrzy** [comment]
thank you so much @jasonsanjose @Brainzyy for your work. i wonder how how i could get css declaration suggestion as i type in SASS

**Comment by gverm** [comment]
@Humphreto I can't help you with that, sorry. But if you have any issues, don't hesitate to contact me. I hope @jasonsanjose can help you.

**Comment by ngomjnhthj** [comment]
@UltraChilly Thank you. It working for me. But I'm missing binding.node inside the win32-ia32-48 folder.
My error:
Error: `libsass` bindings not found in Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-ia32-48\binding.node.

**Comment by gverm** [comment]
@ngomjnhthj try the version from: https://github.com/jasonsanjose/brackets-sass/issues/190

**Comment by ngomjnhthj** [comment]
@gverm Thank you so much. It's working for me.

**Comment by bathanusing** [comment]
@ngomjnhthj i was having the same issue and i just downloaded https://github.com/sass/node-sass-binaries/blob/master/win32-ia32-48_binding.node and cut and paste that file inside a folder "win32-ia32-48" in node-sass/vendor and all works good ;)

**Comment by Rafiozoo** [comment]
https://github.com/jasonsanjose/brackets-sass/issues/190#issuecomment-319950279 this helped to me
