### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by jasonsanjose** [jasonsanjose/brackets-sass#19]
Reported via YouTube https://www.youtube.com/watch?v=xSgkQc48aSw&google_comment_id=z13lw3crpyutv1y5004cgd3wbkrzjliek

I'm having a few problems with the compilation of scss files. I have installed your extension on brackets as well as node.js. My brackets.json is like this:

```
{
    "path": {
        "Common/sass/emkt-projectEditor.css.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "../stylesheets/emkt-projectEditor.css",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": "map",
                "outputStyle": "nested"
            }
        }
    }
}
```

But is not compiling. When i open the scss file, after a while, it shows: "SCSS has timed out after waiting for 10000 ms"

What am I doing wrong?﻿

**Comment by derwaldgeist** [comment]
I've got the very same problem on MacOS, but only if I'm using the Ruby compiler. Compiling a large scss file with many imports and partials will eventually result in a timeout error, as it has used more than 10000ms. It seems as if this is a restriction by Brackets, as the error message is translated to German as well. If I run the sass command on the command line, compilation is done without any errors, so there should be no bug in my files.

**Comment by marley627** [comment]
**my fix**: issue was related to $variables, check that you're referencing them exactly as you've declared them and their value, correct syntax etc. Reload with extensions (f5). Hope this helps someone, stumped me for a bit.

**Comment by Emmathem** [comment]
I can't compile my sass file, getting timeout and sometimes cleanup... what is the solution, please?
No error in my sass file
