### ISSUE TITLE
Doesn't always compile css when file changes

### ISSUE THREAD

**Issue by samuel-clara** [jasonsanjose/brackets-sass#193]
Until now I used Brackets with sass compiler on windows and it worked perfectly, now I'm using it on mac and  when I save a scss file the plugin doesn't always compile the css. No errors showed, I try to install previous versions but the problem is still here.

**Comment by zkelo** [comment]
I have the same problem on Windows. Just reload Brackets (on Windows by F5, i don't know how to do it on Mac).
