### ISSUE TITLE
`libsass` bindings not found.

### ISSUE THREAD

**Issue by zkelo** [jasonsanjose/brackets-sass#195]
When I edit any scss file i given this error:

> Error: `libsass` bindings not found in C:\Users\Александр\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-ia32-48\binding.node. Try reinstalling `node-sass`? at Object.sass.getBinaryPath (C:\Users\Александр\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\extensions.js:148:11) at Object.<anonymous> (C:\Users\Александр\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\index.js:16:36) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Module.require (module.js:468:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Users\Александр\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\render.js:39:12)	

How to fix it?

**Comment by Strydom** [comment]
I'm also getting this problem. How did you fix it @zkelo ?
