### ISSUE TITLE
SASS Pass parameters.

### ISSUE THREAD

**Issue by flaviusemil** [jasonsanjose/brackets-sass#196]
I had a project that I needed to pass some parameters to the sass compiler. And I could not find any method of doing it.
I needed to pass some required ruby modules before the sass compiled.

I think it would be a very useful addition.

**Comment by Taariqq** [comment]
@flaviusemil did you find a solution or did you just move to another solution?
I am kinda new and trying to figure out if I should use this extension or not. Appreciate your answer.
