### ISSUE TITLE
Unusable after installing Brackets 1.11

### ISSUE THREAD

**Issue by ben4d85** [jasonsanjose/brackets-sass#203]
After updating to Brackets 1.11 today, and updating the Brackets SASS extension to 2.0.5, the extension **stopped working** (note that I never had any issues before this).

The error I get when saving a file is:
`cleanup`

If I then save the file again, I get the following error:
```
Error: `libsass` bindings not found in C:\Users\Ben\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-ia32-48\binding.node. Try reinstalling `node-sass`? at Object.sass.getBinaryPath (C:\Users\Ben\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\extensions.js:148:11) at Object.<anonymous> (C:\Users\Ben\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\index.js:16:36) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Users\Ben\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\render.js:39:12) |  
-- | -- | -- | --
```

How can this be fixed, please?

**Comment by kaufsim** [comment]
folder win32-ia32-48 is not present in
 `%APPDATA%\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\`

**Comment by Edwingi** [comment]
Same problem, also using 1.11 & 2.0.5

**Comment by vdGeld** [comment]
The 2.0.7 version attached to issue https://github.com/jasonsanjose/brackets-sass/issues/202 solved it for me;

**Comment by ben4d85** [comment]
Given that this ticket in from 2017, and I haven't used Brackets since, I am closing this ticket.
