### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by awakekat** [jasonsanjose/brackets-sass#29]
Using Windows Vista, I cannot use the extension manager to remove, it just gives a generic error and says brackets will reload. I tried to manually uninstall via Help > show extension folder and deleting the folder itself and I was getting a permissions error. I came to give you this info and realized I had two copies of brackets open at the same time. I closed them both down reopened it and it was able to uninstall the extension. Sorry that it was your extension. This seems to me to be a bug. I was getting another error on another extension I was trying to remove as well. It seems to be ok now, but just letting you know since it looks like you work for adobe. Just passing along the two open app error problem.

Happy Coding

**Comment by Edwingi** [comment]
Seems this has returned.
Having the same problem as stated above.

**Comment by jasonsanjose** [comment]
There are 2 potential workarounds for this uninstall problem:

1. Restart Brackets (make sure you don't have a .sass/.scss file open at startup), then uninstall via the Extension Manager (thanks @rgfx)
2. Quit Brackets, then manually delete the extension at `C:/Users/<your user name>/AppData/Roaming/Brackets/extensions/user/jasonsanjose.brackets-sass/`

I'll close this bug and use #81 to track the actual fix. I'll make sure to update the README too.
