### ISSUE TITLE
Add Ruby sass compiler option

### ISSUE THREAD

**Issue by jasonsanjose** [jasonsanjose/brackets-sass#3]
If the user has the `sass` command line tool installed, allow switching the compiler from the libsass compiler packaged with this extension.

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo Not currently. If you would like to contribute, let me know and I can try to give you some tips.

**Comment by nicolo-ribaudo** [comment]
I'm working on this feature.

Just a question: how should the user choose which compiler to use?
What about a `sass.compiler` option whose value can be `libsass` (default) or `ruby`?

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo `sass.compiler` is perfect. Let me know if I can help. Are you just using a shell via node to call the ruby compiler?

**Comment by nicolo-ribaudo** [comment]
Yes, I'm using the `child_process.exec` method.

I only don't know how to implement the `imagePath` option... it seems that
sass doesn't implement this tool natively. Maybe we can copy the [Compass'
implementation](
https://github.com/Compass/compass/blob/350bcaa544f594bca972aaa29a9bdfddceee5d4f/core/lib/compass/core/sass_extensions/functions/urls.rb#L112)?
(Although I don't know how to do)

Il giorno 22:08 Gio 29/Gen/2015 Jason San Jose <notifications@github.com>
ha scritto:

@nicolo-ribaudo <https://github.com/nicolo-ribaudo> sass.compiler is

**Comment by nicolo-ribaudo** [comment]
What I have done for now: [nicolo-ribaudo/brackets-sass/tree/ruby-compiler](https://github.com/nicolo-ribaudo/brackets-sass/tree/ruby-compiler)

What doesn't work:
- `imagePath`
- Live Preview:
  I think that is because of the long time that Ruby takes to compile the file (more than a second). However, when you hover a selector in the scss code, it is highlighted in the browser.

**Comment by jasonsanjose** [comment]
Confirmed fixed. Targeting release 2.0.
