### ISSUE TITLE
Compass support

### ISSUE THREAD

**Issue by jasonsanjose** [jasonsanjose/brackets-sass#34]
libsass doesn't support Compass http://compass-style.org/ (or vice versa). See https://github.com/sass/libsass/issues/82#issuecomment-51095702.

Compass could be supported if we can leverage the work to swap in the ruby compiler https://github.com/jasonsanjose/brackets-sass/issues/3 to also support using the compass command line tools.

**Comment by nicolo-ribaudo** [comment]
I'm working on this: https://github.com/nicolo-ribaudo/brackets-sass/tree/compass
(Depends on #90)

How should be compass enabled?
```json
{
    "sass.compiler": "ruby",
    "sass.compass": true
}
```
or
```json
{
    "sass.compiler": "ruby",
    "sass.options": {
        "compass": true
    }
}
```

I think the first is better because `sass.options` is "reserved" for libsass' options...

**Comment by jasonsanjose** [comment]
Tagging v2. Need to investigate if new ruby support makes it any easier for compass support. cc @nicolo-ribaudo.

**Comment by nicolo-ribaudo** [comment]
> Need to investigate if new ruby support makes it any easier for compass support

From version 3.1.0 of the Ruby Sass compiler, compass can be enabled with the `--compass` argument
```
sass main.scss main.css --compass
```

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo thanks!

I took a quick look at your branch. Looks pretty solid. I can integrate it into my `v2` branch and start testing.

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo I think I was overly optimistic on this one. While `sass --compass` does work, it doesn't _completely_ account for the `config.rb` project configuration file (see http://compass-style.org/help/documentation/configuration-reference/).

For example, from my limited experience with Compass, users commonly use the spritesheet features. This requires a `images_dir` defined in `config.rb`.

While `sass --compass` did recognize the `images_dir` configuration, it ignores the output directory in `css_dir` (by default `config.rb` has `css_dir = "stylesheets"`).

So, long story short, the generated CSS will end up in the wrong location by default since this extension will save the file next to the input SASS file. Not a big deal, but users familiar with Compass will have to also change the `.brackets.json` file to have a matching output folder.

There's a longer list of command line options to consider as well:

```
compass compile --help

Usage: compass compile [path/to/project] [path/to/project/src/file.sass ...] [options]

Description:
compile project at the path specified or the current directory if not specified.

Options:
        --[no-]sourcemap             Generate a sourcemap during compilation.
        --time                       Display compilation times.
        --debug-info                 Turns on sass's debuging information
        --no-debug-info              Turns off sass's debuging information
    -r, --require LIBRARY            Require the given ruby LIBRARY before running commands.
                                       This is used to access compass plugins without having a
                                       project configuration file.
    -l, --load FRAMEWORK_DIR         Load the framework or extensions found in the FRAMEWORK directory.
    -L, --load-all FRAMEWORKS_DIR    Load all the frameworks or extensions found in the FRAMEWORKS_DIR directory.
    -I, --import-path IMPORT_PATH    Makes files under the IMPORT_PATH folder findable by Sass's @import directive.
    -q, --quiet                      Quiet mode.
        --trace                      Show a full stacktrace on error
        --force                      Allows compass to overwrite existing files.
        --boring                     Turn off colorized output.
    -c, --config CONFIG_FILE         Specify the location of the configuration file explicitly.
        --app APP                    Tell compass what kind of application it is integrating with. E.g. rails
        --app-dir PATH               The base directory for your application.
        --sass-dir SRC_DIR           The source directory where you keep your sass stylesheets.
        --css-dir CSS_DIR            The target directory where you keep your css stylesheets.
        --images-dir IMAGES_DIR      The directory where you keep your images.
        --javascripts-dir JS_DIR     The directory where you keep your javascripts.
        --fonts-dir FONTS_DIR        The directory where you keep your fonts.
    -e, --environment ENV            Use sensible defaults for your current environment.
                                       One of: development (default), production
    -s, --output-style STYLE         Select a CSS output mode.
                                       One of: nested, expanded, compact, compressed
        --relative-assets            Make compass asset helpers generate relative urls to assets.
        --no-line-comments           Disable line comments.
        --http-path HTTP_PATH        Set this to the root of your project when deployed
        --generated-images-path GENERATED_IMAGES_PATH
                                     The path where you generate your images
    -?, -h, --help                   Show this message
```

I think we'll need to reconsider how this works with generating compiler errors and with live preview.

**Comment by jasonsanjose** [comment]
Note to self, this package may come in handy for parsing config.rb https://github.com/Snugug/Compass-Options.

**Comment by jasonsanjose** [comment]
I added basic compass support (file save only, no live preview). See https://github.com/jasonsanjose/brackets-sass/pull/100#issuecomment-76787328 for more details and a link to a test build.

**Comment by jasonsanjose** [comment]
Closing. Will file additional feature work to support compass in live preview.
