### ISSUE TITLE
.brackets.json not doing anything

### ISSUE THREAD

**Issue by robhunt3r** [jasonsanjose/brackets-sass#39]
I put .brackets.json file inside my root folder, restart brackets and everything but it doesn't work.

``` javascript{
    "path": {
        "scss/app.scss": {
            "sass.enabled": true,
            "sass.options": {
                "includePaths": [
                    "bower_components/foundation/scss/"
                ],
                "outputDir": "../css/",
                "imagePath": null,
                "sourceComments": "map",
                "outputStyle": "nested"
            }
        }
    }
}
```

It is rendering inside `scss` folder instead of `css`, and also using `includePaths` isn't working either, as I need to use the full path inside my `@include` otherwise it won't work.

![captura de pantalla 2014-09-23 a la s 00 07 12](https://cloud.githubusercontent.com/assets/5111603/4364875/19454458-42a5-11e4-881d-13e9b2d5feee.png)

Using latest version of brackets and plugin. No other plugins are being used.

**Comment by ghost** [comment]
I had to say 

`"outputDir": "../css",`

Removing the final forward slash, then, for some reason... then it worked

```
{
    "path": {
        "scss/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css",
                "sourceComments": "map",
                "outputStyle": "nested"
            }
        }
    }
}
```
