### ISSUE TITLE
Comments on compiled file

### ISSUE THREAD

**Issue by CydGoblin** [jasonsanjose/brackets-sass#60]
I'm getting comments on compiled files something like
/\* line 20, /Users/Desktop/Web/l/css/lib/variables.scss */

is there a way to stop it?

**Comment by jasonsanjose** [comment]
@Le4nder it should be `"sourceComments`: false`. I've updated the readme and the example.

**Comment by link2pk** [comment]
Hi jason,

I still couldn't be able to figure out how to remove these unnecessary comments from my generated css file.

here are the screen shots:

![output](https://cloud.githubusercontent.com/assets/12784319/8964993/570276ae-3646-11e5-8f1d-22dc08a20d17.png)
![settings](https://cloud.githubusercontent.com/assets/12784319/8964994/5709f5aa-3646-11e5-890b-7d2047fb4c5a.png)


Any help would be greatly appreciated.

**Comment by Turqueso** [comment]
@link2pk i don't see in your `.brackets.json` the part of brackets-sass, just adding `sourceComments`and not the rest won't work. Should be something like:
```
{
{
  "sass.enabled": false,
  "path": {
    "main.scss": {
      "sass.enabled": true,
      "sass.options": {
        "includePaths": [],
        "sourceComments": false,
        "outputStyle": "nested"
      }
    }
  },
  /*everything else in your .brackets.jason */
}
```

**Comment by link2pk** [comment]
@Turqueso  I did something like this:
![done](https://cloud.githubusercontent.com/assets/12784319/8965794/53f8cb8e-364b-11e5-80ab-d183d77a8869.png)

It's working now. Thanks a lot.
