### ISSUE TITLE
False error message (@import rule)

### ISSUE THREAD

**Issue by mikriot** [jasonsanjose/brackets-sass#65]
If the project located is not on the system drive, I get this error:

![error](https://cloud.githubusercontent.com/assets/7242985/5169502/d80525da-7418-11e4-919d-9193c1e8edd6.png)

although the compilation goes well: 

scss

![scss](https://cloud.githubusercontent.com/assets/7242985/5169506/da8fc56c-7418-11e4-93f1-5f73b87df3d5.png)

css

![css](https://cloud.githubusercontent.com/assets/7242985/5170276/88f7d09e-741f-11e4-9f55-6bd22540cbe3.png)

I use windows 8.1, brackets-sass 1.0.2-77 and [bourbon-example].

[bourbon-example]:https://github.com/jasonsanjose/bourbon-example

**Comment by jasonsanjose** [comment]
@mikriot can you still reproduce this?

**Comment by mikriot** [comment]
@jasonsanjose I'm still getting this error :(

**Comment by jasonsanjose** [comment]
@mikriot did you try updating to the latest version 1.0.3?

**Comment by jasonsanjose** [comment]
You could also try syncing to the latest https://github.com/jasonsanjose/bourbon-example. I updated it to include a local partial file for importing.

**Comment by jasonsanjose** [comment]
@mikriot nevermind. I found an issue where the node-sass binary wasn't updated on mac...are you on a mac? Anyway, please try the latest version 1.0.4-83 available in the extension registry and let me know how that works.

**Comment by mikriot** [comment]
> are you on a mac?

No. I use windows.

> try the latest version 1.0.4-83 available in the extension registry and let me know how that works

I updated brackets-sass and downloaded latest version bourbon-example, but the error persists.

**Comment by gbggit** [comment]
I have the same problem on Windows7, latest editor and brackets-sass version.

I accidentally open my css source map and there I found that the generated path is wrong - it search first in C:/, but my project is in D:/. The file looks sth liek this:

{
  "version": 3,
  "file": "01_style.css",
  "sources": [
    "01_style.scss",
    "C:/D:/imports/_reset.scss",
  ]
...
}

If I move my project in C:/, all works like a charm :).

**Comment by jasonsanjose** [comment]
Thanks for hte updates @mikriot and @gbggit. I'll investigate more.

**Comment by jasonsanjose** [comment]
@gbggit your issue regarding `I found that the generated path is wrong - it search first in C:/, but my project is in D:/` is separate from the original one reported. Please see https://github.com/jasonsanjose/brackets-sass/issues/89 instead.

@mikriot I have a test build here https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-105 that fixes several windows-related issues. Can you give it a try and let me know if it works. Thanks!

**Comment by jasonsanjose** [comment]
Fix in #100. Closing.
