### ISSUE TITLE
sourceComments="?"

### ISSUE THREAD

**Issue by stoufdev** [jasonsanjose/brackets-sass#70]
In my .brackets.json, the sourceComments="map" !
When i choose for option none or normal, nothing changes in css.
There is always comments.
My instal is clean, just 2 plugins :  brackets.sass and Extract for Brackets.
Working with 1 html, and 1 scss, that's all.

I'm on OSX 10.8.5.
And brackets is : Version 1.0 version 1.0.0-15191 (release 3f2eb90a4) 
Horodatage de la version : Fri Oct 31 2014 14:26:26 GMT-0700

My .brackets.json

{
    "path": {
        "style.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "style.css",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "nested"
            }
        },
        "scss/imports/*.scss": {
            "sass.enabled": false
        }
    }
}

Any ideas ?

**Comment by jasonsanjose** [comment]
Thanks, @liouh! I missed this change when upgrading to node-sass 1.1.0 https://github.com/sass/node-sass/tree/v1.1.0. I'll update the `README`.

Sorry for the confusion.

**Comment by jasonsanjose** [comment]
I've updated the README and also updated the example project https://github.com/jasonsanjose/bourbon-example.
