### ISSUE TITLE
Issue with configuration file

### ISSUE THREAD

**Issue by bhouszka** [jasonsanjose/brackets-sass#74]
Hi, some time ago I have configured brackets-sass and it was compiling correctly. Recently I have changed my document folder structure, and now it is not working anymore.

My folder structure is following:

- main folder
   - .brackets.json
   - template-files
      - css
      - scss
         - main.scss

     
My .brackets.json file is following:
    
    {
    	"path": {
    		"./template-files/scss/main.scss": {
    			"sass.enabled": true,
    			"sass.options": {
    				"outputDir": "../css/",
    				"includePaths": [],
    				"imagePath": null,
    				"sourceComments": "map",
    				"outputStyle": "nested"
    			},
    			"linting.collapsed": false
    		}
    	}
    }

I would expect the compiled css file to be placed in css folder but instead after compilation it shows up in scss folder next to main.scss file. What am I doing wrong?

**Comment by kevdesdev** [comment]
+1 Having the same problem. Moving the .brackets.json file around the project directory didn't work. 

To keep my file structure intact for the time being I just did quick hack by adding @import reference in the 'supposedly compiled' css file to the actual file that brackets-sass compiled. It works with Live Preview too.

**Comment by jasonsanjose** [comment]
@bhouszka Typo? You said the folder is "template files" but your .json example shows `template-files` with a hyphen.

**Comment by bhouszka** [comment]
Hi @jasonsanjose,

I had a typo in the comment above (corrected now). The folder name is template-files and it is correctly written in config file. I have checked it at least 10 times :)

**Comment by Turqueso** [comment]
@bhouszka I have a similar structure and it's working. I see you have
```"./template-files/scss/main.scss": {```
I think it should be
```"template-files/scss/main.scss": {``` ?

Also take a look at #70

**Comment by bhouszka** [comment]
@Turqueso 

    "./template-files/scss/main.scss"
and
    "template-files/scss/main.scss"
is the same. But for some reason this was causing the issue. Now it works. Thank you!

**Comment by jasonsanjose** [comment]
Closing. Thanks for the help @Turqueso
