### ISSUE TITLE
Invalid property name

### ISSUE THREAD

**Issue by bhouszka** [jasonsanjose/brackets-sass#75]
Hi,

I have an SCSS file which looks following:

    @import '../helpers/mixins.scss';
    @import '../helpers/variables.scss';
    .primary-tomatored {
        ...
    }

When I try to compile this file it doesn't work. When I check for the errors it says that:

    3 invalid property name	.primary-tomatored {

What could be invalid in my scss file? How can I fix this?

**Comment by jasonsanjose** [comment]
@bhouszka did you figure out the issue? I see you closed this bug recently.

**Comment by MrYakobo** [comment]
Kinda old, but ran into this issue as well. The solution was that I was writing in `.SASS` when I was using curly braces (the `.SCSS`-syntax), and as such it was my own fault - renaming the file to `style.scss` solved my problem 100%. You might want to "make this official", I can totally see more people than I run into this.
Oh and btw thank you for such an awesome extension. I really can't figure how I can live without it. :)
