### ISSUE TITLE
Every thing is working, But!!!

### ISSUE THREAD

**Issue by modymok** [jasonsanjose/brackets-sass#77]
Hi,

i have a weird issues here, every thing is work but when i edit the .scss file an notification comes saying "SCSS Lint has timed out after waiting for 10000 ms"

And is the a way to get code hinting of the bourbon lib in brackets ??

**Comment by ankvell** [comment]
have the same error

**Comment by jasonsanjose** [comment]
@modymok are you using Compass? Unfortunately libsass doesn't return detailed error messages when it encounters unknown syntax.

**Comment by modymok** [comment]
@jasonsanjose no i m not using Compass!, is there any intellisense for it

**Comment by jasonsanjose** [comment]
@modymok can you update to the latest 1.0.4-83? The update is in the extension manager now.

**Comment by modymok** [comment]
Thanks
