### ISSUE TITLE
@imports break live preview on Windows

### ISSUE THREAD

**Issue by velvetkevorkian** [jasonsanjose/brackets-sass#8]
Using `@import`s seems to have issues with live preview on Windows. I'm setting up a basic Foundation project and importing a single partial, `_grid.scss`. My main `style.scss` compiles fine on save (using both the extension and the regular Sass Ruby command line), and live preview works when the import is removed, but with it present each keypress results in the following error in dev tools:

```
ENOENT, no such file or directory 'C:\Users\Kyle\AppData\Local\Temp\brackets-sass\wamp\www\socialDigital2014\bower_components\foundation\scss\foundation\components\_grid.scss'
```

The live preview indicator stays red. Everything works as expected when I load it in OS X, so I don't _think_ this is an issue with my paths. 

This is my `.brackets.json`: 

```
{
    "path": {
        "scss/style.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "/../css/style.css",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": "map",
                "outputStyle": "nested"
            }
        }
    }
}
```

Brackets sprint 38, Windows 7 Home Premium x64, OS X Mavericks.

**Comment by lucascosta** [comment]
I'm having the same problem in Windows 8 and Boostrap. When I change a variable in the _variables.scss file the Live Preview breaks down. Is there any way I could get you more information?

**Comment by jasonsanjose** [comment]
@lucascosta can you try this dev build https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-105 to see if your issue is fixed?

**Comment by lucascosta** [comment]
@jasonsanjose , I won't be working on Windows any more since I changed jobs, so I can't really test that for you in the same environment. Thank you so much for your attention, though.

**Comment by paulowashington** [comment]
Bracket is fantastic, but I'm not able to make the sass build work properly. It seems to be a big problem .. I reviewed the internet but I did not find the solution.
Problems with my project:

> **1.** Compile in the folder (scss) and not in the one I want (css);
> **2.** Only compiles if I edit the file (main.scss) when editing the files that are imported nothing happens.

* I installed the ruby ​​to see if it worked but it is as before without it.
* Use windows 10

Please someone help me!

> my JSON:

    "sass.enabled": false,
    "path": {
        "scss/main.scss": {
        "sass.compiler": "ruby",
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "compressed"
            }
        }
    }
}

> my folder estructure

**css**
       - files
**scss**
       - files included in main with @includes type(_header.scss, footer_scss)
       - main.scss
**brackets.json**
