### ISSUE TITLE
Errors on install and uninstall.

### ISSUE THREAD

**Issue by equinox** [jasonsanjose/brackets-sass#81]
I tried this out just before the last update to it, since then, when it updated it gave me an error saying it couldn't install the update then just now when trying to uninstall it's again giving me an error saying it cannot uninstall it.

I'm using Brackets 1.1 and Windows 7.

**Comment by nicolo-ribaudo** [comment]
You can uninstall the extension by deleting the `C:\Users\<Your Username>\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass` folder.

**Comment by jasonsanjose** [comment]
@Equinoxdawg If you could send me the errors you get on uninstall, that would be great. 

1. Debug > Show Developer Tools
2. Try Uninstall
3. Copy console log from dev tools

Thanks!

**Comment by Equinoxdawg** [comment]
I had done what you suggested Nicolo just after posting this issue, thankfully it worked. I have no reinstalled and was able to reproduce. I opened the dev tools, but there was nothing new between opening the tools and it giving me the error and reloading anyway. It now shows after reload: " GET file:///C:/Users/name/AppData/Roaming/Brackets/extensions/user/jasonsanjose.brackets-sass/main.js net::ERR_FILE_NOT_FOUND
ErrorNotification.js:125 [Extension] failed to load C:/Users/name/AppData/Roaming/Brackets/extensions/user/jasonsanjose.brackets-sass - Module does not exist: file:///C:/Users/name/AppData/Roaming/Brackets/extensions/user/jasonsanjose.brackets-sass/main.js"

**Comment by ofhouse** [comment]
When I try to uninstall everything but this [file](https://github.com/jasonsanjose/brackets-sass/blob/master/node/1.1.4-3/node_modules/node-sass/bin/win32-ia32-v8-3.14/binding.node) gets deleted.

So I guess this file causes the issue, Debug Console is empty.

**Comment by jasonsanjose** [comment]
I think I know what's causing this now. The compiler runs as a child processes (see https://github.com/jasonsanjose/brackets-sass/blob/master/node/1.1.4-3/SASSDomain.js#L173) and I'm not killing the process when an remove/upgrade happens. 

This will be a tricky one to fix and might require something drastic:

1. Quit and manual delete and/or
2. Change the extension ID so that the next version is not an upgrade, but a completely separate extension

Let me think about this a bit.

**Comment by jasonsanjose** [comment]
If my theory is right, users should be able to uninstall if the compiler hasn't run in the current session of Brackets. For example:

1. Quit and restart Brackets
2. Don't compile or view any .sass/.scss files
3. Remove the extension via extension manager

Could be the same cause as these uninstall bugs:

* https://github.com/jasonsanjose/brackets-sass/issues/29
* https://github.com/jasonsanjose/brackets-sass/issues/84

**Comment by ofhouse** [comment]
@jasonsanjose I've tested it (started Brackets with no files open & empty project-folder) but still got the same error on uninstalling.

The workaround does not work I guess ^^

**Comment by jasonsanjose** [comment]
@ofhouse can you try a manual uninstall (instead of extension manager) instead? https://github.com/jasonsanjose/brackets-sass/wiki/Manual-Uninstall

**Comment by nicolo-ribaudo** [comment]
@jasonsanjose Are you working on this bug?

**Comment by jasonsanjose** [comment]
Not currently. I'll take a look at you PR. Thanks!

**Comment by bitbay** [comment]
Quoting the wiki:
> Some users have reported issues on Windows that prevent uninstalling the extension.

Same issue on Debian as well.
