### ISSUE TITLE
scss random() function not compiling in bracket

### ISSUE THREAD

**Issue by paulsjohn** [jasonsanjose/brackets-sass#94]
scss random() function not compiling in bracket editor

**Comment by nicolo-ribaudo** [comment]
This extension uses node-sass v1.1.4, which uses libsass v3.0.1. The `random()` function is supported by libsass from version 3.1.0...

If you have the Ruby Sass compiler installed, you can try to use [this branch](https://github.com/nicolo-ribaudo/brackets-sass/tree/ruby-compiler), which can use that compiler (By setting `"sass.compiler": "ruby"` in your `.brackets.json`)

**Comment by jasonsanjose** [comment]
@paulsjohn You can try the latest dev build here https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-101 (download the zip, open extension manager, then drag the zip from your file system to the drop zone). It include the latest libsass which supports `random()`.

If you have problems uninstalling the current extension, try the workaround here https://github.com/jasonsanjose/brackets-sass/issues/81#issuecomment-76223733.

**Comment by jasonsanjose** [comment]
Confirmed fixed in #100

**Comment by jasonsanjose** [comment]
Closing
