### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by awakekat** [jasonsanjose/brackets-sass#98]
I have created a brackets.json file in the root if my project directory.
contents: 

```
{
  "path": {
    "style.sass": {
        "sass.enabled": false,
        "sass.options": {
            "outputDir": "../css/",
            "includePaths": [],
            "imagePath": null,
            "sourceComments": true,
            "outputStyle": "expanded"
          }
        }
    }
}
```

when making changes to the style.sass file a style.css.map file is created with this inside:

```
{
  "version": 3,
  "file": "style.css",
  "sources": [
    "style.sass"
  ],
  "names": [],
  "mappings": ";AAAA;EACE,YAAY;;;AACd;EACE,OAAO",
  "sourceRoot": ""
}
```

In the brackets file I have changed the "outputDir" to relative and absolute paths and no matter what I do nothing gets sent to a css folder in the root directory.
Everything is output into the sass folder including the style.css. 
What must the brackets.json file say in order to overwrite the outputDir to a css folder in the root directory?

**Comment by nicolo-ribaudo** [comment]
1. The file should be named .brackets.json (With the . at the start)
2. If you write `sass.enabled: false`, files won't be compiled.

Il giorno 17:35 Dom 22/Feb/2015 Katherine Wakefield <
notifications@github.com> ha scritto:

**Comment by jasonsanjose** [comment]
@awakekat based on your report, your project root looks like this:

```
/
--style.sass
--css/
--.brackets.json
```

However you also mentioned a `sass` folder, but your `.brackets.json` implies your file is at the project root `/style.sass` and not in a subfolder. 

If I understood you correctly, you want your `.brackets.json` file to look like this:

```
{
  "path": {
    "style.sass": {
        "sass.enabled": true,
        "sass.options": {
            "outputDir": "css/",
            "includePaths": [],
            "imagePath": null,
            "sourceComments": true,
            "outputStyle": "expanded"
          }
        }
    }
}
```

Note @nicolo-ribaudo's comment about setting `"sass.enabled": true`.

It would be helpful if you could show what your project tree looks like to sanity check the paths. Thanks.

**Comment by awakekat** [comment]
Thanks I got it working. Yes the dot was missing and some other tweaks got it going. Thanks for the help.
